FROM debian:buster

LABEL maintainer="Colin Wilson colin@wyveo.com"

# Let the container know that there is no tty
ENV DEBIAN_FRONTEND noninteractive
ENV NGINX_VERSION 1.17.9-1~buster
ENV php_conf /etc/php/5.6/fpm/php.ini
ENV fpm_conf /etc/php/5.6/fpm/pool.d/www.conf
ENV COMPOSER_VERSION 1.9.3

# Install Basic Requirements
RUN buildDeps='curl gcc make autoconf libc-dev zlib1g-dev pkg-config' \
    && set -x \
    && sed -i "s/deb.debian.org/mirrors.tuna.tsinghua.edu.cn/g" /etc/apt/sources.list \
    && sed -i "s/security.debian.org/mirrors.tuna.tsinghua.edu.cn/g" /etc/apt/sources.list \
    && apt-get update \
    && apt-get install --no-install-recommends $buildDeps --no-install-suggests -q -y gnupg2 dirmngr wget apt-transport-https lsb-release ca-certificates librabbitmq-dev libssl-dev \
    && \
    NGINX_GPGKEY=573BFD6B3D8FBC641079A6ABABF5BD827BD9BF62; \
	  found=''; \
	  for server in \
      hkp://ipv4.pool.sks-keyservers.net \
		  ha.pool.sks-keyservers.net \
		  hkp://keyserver.ubuntu.com:80 \
		  hkp://p80.pool.sks-keyservers.net:80 \
		  pgp.mit.edu \
	  ; do \
		  echo "Fetching GPG key $NGINX_GPGKEY from $server"; \
		  apt-key adv --batch --keyserver "$server" --keyserver-options timeout=10 --recv-keys "$NGINX_GPGKEY" && found=yes && break; \
	  done; \
    test -z "$found" && echo >&2 "error: failed to fetch GPG key $NGINX_GPGKEY" && exit 1; \
    echo "deb http://nginx.org/packages/mainline/debian/ buster nginx" >> /etc/apt/sources.list \
    && wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg \
    && echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/php.list \
    && apt-get update \
    && apt-get install --no-install-recommends --no-install-suggests -q -y \
            apt-utils \
            nano \
            zip \
            unzip \
            python-pip \
            python-setuptools \
            git \
            libmemcached-dev \
            libmemcached11 \
            libmagickwand-dev \
            nginx=${NGINX_VERSION} \
            php5.6-fpm \
            php5.6-cli \
            php5.6-bcmath \
            php5.6-dev \
            php5.6-common \
            php5.6-json \
            php5.6-opcache \
            php5.6-readline \
            php5.6-mbstring \
            php5.6-mcrypt \
            php5.6-curl \
            php5.6-gd \
            php5.6-mysql \
            php5.6-zip \
            php5.6-pgsql \
            php5.6-intl \
            php5.6-xml \
            php5.6-soap \
            php5.6-sqlite3 \
            php-pear \
    && pecl -d php_suffix=5.6 install -o -f redis-2.2.7 memcached-2.1.0 yac-0.9.2 yaf-2.3.5 mongodb-1.7.4 amqp-1.6.1 \
    && mkdir -p /run/php \
    && pip install wheel \
    && pip install supervisor supervisor-stdout \
    && echo "#!/bin/sh\nexit 0" > /usr/sbin/policy-rc.d \
    && rm -rf /etc/nginx/conf.d/default.conf \
    && sed -i -e "s/;cgi.fix_pathinfo=1/cgi.fix_pathinfo=0/g" ${php_conf} \
    && sed -i -e "s/memory_limit\s*=\s*.*/memory_limit = 256M/g" ${php_conf} \
    && sed -i -e "s/upload_max_filesize\s*=\s*2M/upload_max_filesize = 100M/g" ${php_conf} \
    && sed -i -e "s/post_max_size\s*=\s*8M/post_max_size = 100M/g" ${php_conf} \
    && sed -i -e "s/variables_order = \"GPCS\"/variables_order = \"EGPCS\"/g" ${php_conf} \
    && sed -i -e "s/;daemonize\s*=\s*yes/daemonize = no/g" /etc/php/5.6/fpm/php-fpm.conf \
    && sed -i -e "s/;catch_workers_output\s*=\s*yes/catch_workers_output = yes/g" ${fpm_conf} \
    && sed -i -e "s/pm.max_children = 5/pm.max_children = 4/g" ${fpm_conf} \
    && sed -i -e "s/pm.start_servers = 2/pm.start_servers = 3/g" ${fpm_conf} \
    && sed -i -e "s/pm.min_spare_servers = 1/pm.min_spare_servers = 2/g" ${fpm_conf} \
    && sed -i -e "s/pm.max_spare_servers = 3/pm.max_spare_servers = 4/g" ${fpm_conf} \
    && sed -i -e "s/pm.max_requests = 500/pm.max_requests = 200/g" ${fpm_conf} \
    && sed -i -e "s/www-data/nginx/g" ${fpm_conf} \
    && sed -i -e "s/^;clear_env = no$/clear_env = no/" ${fpm_conf} \
    && echo "extension=redis.so" > /etc/php/5.6/mods-available/redis.ini \
    && echo "extension=memcached.so" > /etc/php/5.6/mods-available/memcached.ini \
    && echo "extension=yac.so" > /etc/php/5.6/mods-available/yac.ini \
    && echo "extension=yaf.so" > /etc/php/5.6/mods-available/yaf.ini \
    && echo "extension=mongodb.so" > /etc/php/5.6/mods-available/mongodb.ini \
    && echo "extension=amqp.so" > /etc/php/5.6/mods-available/amqp.ini \
    && ln -sf /etc/php/5.6/mods-available/redis.ini /etc/php/5.6/fpm/conf.d/20-redis.ini \
    && ln -sf /etc/php/5.6/mods-available/redis.ini /etc/php/5.6/cli/conf.d/20-redis.ini \
    && ln -sf /etc/php/5.6/mods-available/memcached.ini /etc/php/5.6/fpm/conf.d/20-memcached.ini \
    && ln -sf /etc/php/5.6/mods-available/memcached.ini /etc/php/5.6/cli/conf.d/20-memcached.ini \
    && ln -sf /etc/php/5.6/mods-available/yac.ini /etc/php/5.6/fpm/conf.d/20-yac.ini \
    && ln -sf /etc/php/5.6/mods-available/yac.ini /etc/php/5.6/cli/conf.d/20-yac.ini \
    && ln -sf /etc/php/5.6/mods-available/yaf.ini /etc/php/5.6/fpm/conf.d/20-yaf.ini \
    && ln -sf /etc/php/5.6/mods-available/yaf.ini /etc/php/5.6/cli/conf.d/20-yaf.ini \
    && ln -sf /etc/php/5.6/mods-available/mongodb.ini /etc/php/5.6/fpm/conf.d/20-mongodb.ini \
    && ln -sf /etc/php/5.6/mods-available/mongodb.ini /etc/php/5.6/cli/conf.d/20-mongodb.ini \
    && ln -sf /etc/php/5.6/mods-available/amqp.ini /etc/php/5.6/fpm/conf.d/20-amqp.ini \
    && ln -sf /etc/php/5.6/mods-available/amqp.ini /etc/php/5.6/cli/conf.d/20-amqp.ini

RUN curl -o /tmp/composer-setup.php https://getcomposer.org/installer \
  && curl -o /tmp/composer-setup.sig https://composer.github.io/installer.sig \
  && php -r "if (hash('SHA384', file_get_contents('/tmp/composer-setup.php')) !== trim(file_get_contents('/tmp/composer-setup.sig'))) { unlink('/tmp/composer-setup.php'); echo 'Invalid installer' . PHP_EOL; exit(1); }" \
  && php /tmp/composer-setup.php --no-ansi --install-dir=/usr/local/bin --filename=composer --version=${COMPOSER_VERSION} && rm -rf /tmp/composer-setup.php

# Clean up
RUN rm -rf /tmp/pear \
    && apt-get purge -y --auto-remove $buildDeps \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Supervisor config
ADD ./supervisord.conf /etc/supervisord.conf

# Override nginx's default config
ADD ./default.conf /etc/nginx/conf.d/default.conf

# Override default nginx welcome page
COPY html /usr/share/nginx/html

# Add Scripts
ADD ./start.sh /start.sh

EXPOSE 80

CMD ["/start.sh"]
